# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/stleraburg/mnist_riscv/mnist_riscv.runs/synth_1/riscv_core.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/stleraburg/mnist_riscv/mnist_riscv.cache/wt [current_project]
set_property parent.project_path C:/Users/stleraburg/mnist_riscv/mnist_riscv.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/stleraburg/mnist_riscv/mnist_riscv.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/include.v
set_property file_type "Verilog Header" [get_files C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/include.v]
read_mem {
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_19.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_9.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_27.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_27.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_28.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_3.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_8.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_19.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_28.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/sigContent.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_3.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_4.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_18.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_0.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_18.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_29.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_6.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_0.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_7.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_6.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_1.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_3.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_16.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_29.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_25.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_11.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_17.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_12.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_9.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_10.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_13.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_5.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_26.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_2.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_5.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_5.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_8.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_2.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_2.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_21.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_22.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_4.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_14.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_8.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_1.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_14.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_9.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_23.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_7.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_22.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_8.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_22.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_6.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_23.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_24.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_21.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_7.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_15.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_15.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_5.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_2.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_20.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_6.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_0.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_11.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_25.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_12.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_17.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_8.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_20.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_24.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_10.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_5.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_26.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_13.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_2.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_16.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_1.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_29.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_6.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_3.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_4.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_19.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_2.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_19.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/data_nn.mem
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_1.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_27.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_3.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_6.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_5.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_7.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_28.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_28.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_9.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_4.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_3.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_8.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_11.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_10.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_27.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_10.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_25.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_12.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_20.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_17.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_16.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_11.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_6.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_4.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_9.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_1.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_0.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_1.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_4.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_3.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_26.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_7.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_0.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_29.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/mnist.mem
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_13.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_18.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_1.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_8.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_14.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_7.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_14.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_4.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_0.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_21.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_2.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_15.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_15.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_9.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_5.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_24.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_24.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_8.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_23.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_7.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_20.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_23.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_0.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_25.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_4_1.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_4.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_4_5.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_7.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_0.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_16.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_17.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_12.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_3_3.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_2_2.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_13.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_2_26.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_18.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_21.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_3_9.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_22.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/b_1_9.mif
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/nnFPGA_mnist/w_b/w_1_6.mif
}
read_verilog -library xil_defaultlib {
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/ALU.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/ALU_control.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/AND_gate.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/OR_gate.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/ReLU.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/adder.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/control_unit.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/data_memory.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/debounce.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/fcnn.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/hardmax.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/imm_gen.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/layer1.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/layer2.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/layer3.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/layer4.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/mux1.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/mux2.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/mux3.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/mux4.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/mux5.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/mux6.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/mux7.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/neuron.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/program_counter.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/reg_file.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/rocc_if.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/scratchpad_mem.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/sigROM.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/uart_rx.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/uart_tx.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/weight_memory.v
  C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/imports/new/riscv_core.v
}
read_ip -quiet C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/stleraburg/mnist_riscv/mnist_riscv.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/stleraburg/mnist_riscv/mnist_riscv.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/stleraburg/mnist_riscv/mnist_riscv.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/constrs_1/imports/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/stleraburg/mnist_riscv/mnist_riscv.srcs/constrs_1/imports/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top riscv_core -part xc7z045ffg900-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_core.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_core_utilization_synth.rpt -pb riscv_core_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
